### ISSUE TITLE
Best performance between Blob, FileReader->base64 and Uint8Array->base64 ?

### ISSUE THREAD

**Issue by tdurand** [tbicr/OfflineMap#5]
Hey, nice project !

I'm trying things out, but i'm wondering which of these methods will have the best performance for rendering the map ? 

Thanks

**Comment by tbicr** [comment]
Hi, I do not have tests, but as I remember all of them had not very good with performance especially for mobile devices.

**Comment by tdurand** [comment]
Yeah, i will try will several, but i think blob should be the better one as you do not have to convert stuff, but i do not know. I'm trying to hack a project i will tell you more ! 

Thanks anyway your work helps me a lot bootstrapping stuff !

**Comment by tbicr** [comment]
Fill free to ask if something not clear there.
